# Generated by Django 5.0.6 on 2024-06-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_equipment_dimension1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='dimension1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='dimension2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='dimension3',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='storage_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='supplier_art',
            field=models.CharField(max_length=100),
        ),
    ]
